option("aten-native")
    set_default(false)
    set_showmenu(true)
    set_description("Build native ATen structural and upstream CUDA Hadamard reference backends")
option_end()
option("torch-root")
    set_default("")
    set_showmenu(true)
    set_description("Actual PyTorch package root containing include/ and lib/")
option_end()
option("aten-cxx11-abi")
    set_default("")
    set_showmenu(true)
    set_description("Explicit torch._C._GLIBCXX_USE_CXX11_ABI value; current native runtime is validated with 1")
option_end()
option("hadamard-source")
    set_default("")
    set_showmenu(true)
    set_description("Unmodified fast-hadamard-transform source checkout")
option_end()
option("hadamard-object")
    set_default("")
    set_showmenu(true)
    set_description("Upstream CUDA-only object built for the actual GPU; not the Python extension .so")
option_end()

if has_config("aten-native") then
    local torch_root = get_config("torch-root")
    local hadamard_source = get_config("hadamard-source")
    local hadamard_object = get_config("hadamard-object")
    target("llaisys-aten-native")
        set_kind("static")
        set_default(false)
        set_languages("cxx20")
        set_warnings("all", "error")
        add_cxflags("-fPIC")
        add_deps("llaisys-native-tensor")
        add_includedirs("..", {public = true})
        add_includedirs(path.join(torch_root, "include"), path.join(torch_root, "include/torch/csrc/api/include"),
                        {system = true})
        add_includedirs(path.join(hadamard_source, "csrc"), {system = true})
        add_files("../src/backends/aten/structural_kernel.cpp", "../src/backends/hadamard/native_kernel.cpp")
        if hadamard_object and hadamard_object ~= "" then add_files(hadamard_object) end
        add_defines("_GLIBCXX_USE_CXX11_ABI=1")
        add_linkdirs(path.join(torch_root, "lib"), {public = true})
        add_links("torch_cuda", "torch_cpu", "c10_cuda", "c10", "cudart", "dl", {public = true})
        add_ldflags("-Wl,--no-as-needed", {force = true, public = true})
        add_rpathdirs(path.join(torch_root, "lib"), {public = true})
        on_load(function (target)
            if not has_config("nv-gpu") or tostring(get_config("aten-cxx11-abi")) ~= "1" then
                raise("native ATen requires NVIDIA and an explicitly verified --aten-cxx11-abi=1")
            end
            if not os.isfile(path.join(torch_root, "include/ATen/ATen.h"))
                or not os.isfile(path.join(torch_root, "lib/libtorch_cuda.so")) then
                raise("--torch-root must be the actual compatible PyTorch package")
            end
            if not os.isfile(path.join(hadamard_source, "csrc/fast_hadamard_transform.h"))
                or not os.isfile(hadamard_object) then
                raise("provide the upstream Hadamard source and its compatible CUDA-only object")
            end
            import("detect.sdks.find_cuda")
            local cuda = find_cuda()
            assert(cuda, "native ATen/Hadamard requires the detected CUDA toolkit")
            target:add("includedirs", cuda.includedirs)
            target:add("linkdirs", cuda.linkdirs, {public = true})
        end)
    target_end()
end
